### ISSUE TITLE
TypeError interrupts project generation dialogue

### ISSUE THREAD

**Issue by Talamantez** [nexumAG/generator-atomic#105]
Taking a look at Yo Atomic today, I ran into the following error while trying to create a project. I'm leaving the whole dialogue here for clarity. Any help is appreciated - thanks!:

I try to create a project with 
```yo atomic```

The generator dialogue proceeds as expected
```generator-atomic version: 1.5.1
? Name of the new Project a
? Choose the javascript namespace (should be short
, lowercase, no special-chars) 
? Whats your name? (the author) 
? Would you like to have a navigtion Yes
? What would you like to use to undefined? Bootstr
ap 4 (Sass)
? Would you like to use Galen for Layout-Tests? No
? Would you like to include Karma / Jasmine for JS
 Unit-Tests? No
? Would you like to camelize your sub-module names
 (highly recommended)? Yes```

...and throws an error here:
```TypeError: Cannot read property 'replace' of undefined
    at Generator.<anonymous> (/usr/local/lib/node_modules/generator-atomic/app/index.js:102:36)
    at Generator.<anonymous> (/usr/local/lib/node_modules/generator-atomic/node_modules/yeoman-generator/lib/base.js:239:7)```

**Comment by bpaetzold** [comment]
Hi @Talamantez,

can you please provide the version number, you're currently using? Thanks!

**Comment by Talamantez** [comment]
Thanks @bpaetzold,

I'm using Yeoman 2.0.0

**Comment by BobbyBabes** [comment]
This is probably not relevant anymore.
But there was/is something funny going on with this prompt. The `undefined` in it looks wrong.
 : `? What would you like to use to undefined? Bootstrap 4 (Sass)`.

This code :
```JavaScript
{
      type: 'list',
      name: 'cssPreprocessor',
      message: 'What would you like to use to ' + 'write styles'.blue + '?',
      choices: ['Bootstrap 4 (Sass)', 'Bootstrap 3 (Less)'],

      // Cut code from here for brevity.
},
```
[https://github.com/nexumAG/generator-atomic/blob/master/app/index.js#L57](https://github.com/nexumAG/generator-atomic/blob/master/app/index.js#L57)
